import type { CatalogEntry } from './types';

export const CATALOG: CatalogEntry[] = [
  {
    name: 'Avatar',
    description:
      "Circular identity badge showing a person's auto-generated initials and color from their name.",
    acceptsChildren: false,
    childrenKind: 'none',
    props: [
      {
        name: 'name',
        type: 'string',
        required: true,
        description:
          "Person's name; drives both the initials and the background tint.",
      },
      {
        name: 'size',
        type: 'enum',
        enum: ['sm', 'md', 'lg'],
        required: false,
        description: 'Diameter of the circle. Default md.',
      },
      {
        name: 'color',
        type: 'enum',
        enum: ['tint1', 'tint2', 'tint3'],
        required: false,
        description: 'Override the auto-hashed identity tint.',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'AvatarGroup',
    description:
      'Stacks multiple Avatar elements into an overlapping row with optional +N overflow chip.',
    acceptsChildren: true,
    childrenKind: 'nodes',
    props: [
      {
        name: 'size',
        type: 'enum',
        enum: ['sm', 'md', 'lg'],
        required: false,
        description:
          'Uniform diameter applied to every avatar in the group. Default md.',
      },
      {
        name: 'max',
        type: 'number',
        required: false,
        description:
          'Cap visible avatars; the remainder collapse into a +N chip.',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'Badge',
    description:
      'Small inline status chip with optional leading icon and a text label.',
    acceptsChildren: true,
    childrenKind: 'nodes',
    props: [
      {
        name: 'status',
        type: 'enum',
        enum: ['neutral', 'success', 'warning', 'error', 'info'],
        description: 'Selects surface and accent colour; default neutral.',
        required: false,
      },
      {
        name: 'size',
        type: 'enum',
        enum: ['sm', 'md'],
        description: 'Density scale; default md.',
        required: false,
      },
      {
        name: 'icon',
        type: 'node',
        description:
          'Optional leading Lucide icon, auto-sized and tinted by status.',
        required: false,
      },
      {
        name: 'as',
        type: 'other',
        description: 'Element Badge renders as; default span.',
        required: false,
      },
    ],
    subcomponents: [],
  },
  {
    name: 'Box',
    description:
      'Token-bound layout primitive; use for any flex/grid container or spacing/sizing/positioning wrapper (defaults to a flex div).',
    acceptsChildren: true,
    childrenKind: 'nodes',
    props: [
      {
        name: 'as',
        type: 'other',
        description: "Element or component to render as (default 'div').",
      },
      {
        name: 'display',
        type: 'enum',
        enum: [
          'block',
          'flex',
          'inline-flex',
          'inline',
          'grid',
          'inline-grid',
          'none',
        ],
        description: "Display mode; defaults to 'flex'.",
      },
      {
        name: 'direction',
        type: 'enum',
        enum: ['row', 'column', 'row-reverse', 'column-reverse'],
        description: 'Flex main-axis direction.',
      },
      {
        name: 'align',
        type: 'enum',
        enum: ['start', 'center', 'end', 'stretch', 'baseline'],
        description: 'Cross-axis alignment (align-items).',
      },
      {
        name: 'justify',
        type: 'enum',
        enum: ['start', 'center', 'end', 'between', 'around', 'evenly'],
        description: 'Main-axis distribution (justify-content).',
      },
      {
        name: 'wrap',
        type: 'enum',
        enum: ['nowrap', 'wrap', 'wrap-reverse'],
        description: 'Flex wrapping behavior.',
      },
      {
        name: 'gap',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
        ],
        description: 'Gap between children (space token).',
      },
      {
        name: 'rowGap',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
        ],
        description: 'Row gap (space token).',
      },
      {
        name: 'columnGap',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
        ],
        description: 'Column gap (space token).',
      },
      {
        name: 'flex',
        type: 'enum',
        enum: ['none', 'auto', 'initial', '1'],
        description: 'Flex shorthand for the item.',
      },
      {
        name: 'grow',
        type: 'boolean',
        description: 'Allow item to grow (flex-grow).',
      },
      {
        name: 'shrink',
        type: 'boolean',
        description: 'Allow item to shrink (flex-shrink).',
      },
      {
        name: 'basis',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'auto',
          'full',
          'content',
        ],
        description: 'Flex-basis (space token or keyword).',
      },
      {
        name: 'alignSelf',
        type: 'enum',
        enum: ['start', 'center', 'end', 'stretch', 'baseline', 'auto'],
        description: 'Override cross-axis alignment for this item.',
      },
      {
        name: 'justifySelf',
        type: 'enum',
        enum: ['start', 'center', 'end', 'stretch', 'auto'],
        description: 'Justify-self for grid item.',
      },
      {
        name: 'p',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
        ],
        description: 'Padding all sides (space token).',
      },
      {
        name: 'px',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
        ],
        description: 'Horizontal padding.',
      },
      {
        name: 'py',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
        ],
        description: 'Vertical padding.',
      },
      {
        name: 'pt',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
        ],
        description: 'Padding top.',
      },
      {
        name: 'pr',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
        ],
        description: 'Padding right.',
      },
      {
        name: 'pb',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
        ],
        description: 'Padding bottom.',
      },
      {
        name: 'pl',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
        ],
        description: 'Padding left.',
      },
      {
        name: 'm',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'auto',
        ],
        description: "Margin all sides (space token or 'auto').",
      },
      {
        name: 'mx',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'auto',
        ],
        description: 'Horizontal margin.',
      },
      {
        name: 'my',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'auto',
        ],
        description: 'Vertical margin.',
      },
      {
        name: 'mt',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'auto',
        ],
        description: 'Margin top.',
      },
      {
        name: 'mr',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'auto',
        ],
        description: 'Margin right.',
      },
      {
        name: 'mb',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'auto',
        ],
        description: 'Margin bottom.',
      },
      {
        name: 'ml',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'auto',
        ],
        description: 'Margin left.',
      },
      {
        name: 'width',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'space24',
          'space32',
          'space40',
          'space48',
          'space64',
          'space80',
          'space96',
          'space128',
          'space160',
          'space192',
          'space240',
          'full',
          'auto',
          'fit',
          'min',
          'max',
          'screen',
          'page',
        ],
        description:
          'Width — a space step (space0..space20 fine, space24..space240 = 96..960px for wider containers) or a keyword (full/auto/fit/min/max/screen/page).',
      },
      {
        name: 'height',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'space24',
          'space32',
          'space40',
          'space48',
          'space64',
          'space80',
          'space96',
          'space128',
          'space160',
          'space192',
          'space240',
          'full',
          'auto',
          'fit',
          'min',
          'max',
          'screen',
          'page',
        ],
        description: 'Height (space token or sizing keyword).',
      },
      {
        name: 'minWidth',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'space24',
          'space32',
          'space40',
          'space48',
          'space64',
          'space80',
          'space96',
          'space128',
          'space160',
          'space192',
          'space240',
          'full',
          'auto',
          'fit',
          'min',
          'max',
          'screen',
          'page',
        ],
        description: 'Minimum width.',
      },
      {
        name: 'maxWidth',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'space24',
          'space32',
          'space40',
          'space48',
          'space64',
          'space80',
          'space96',
          'space128',
          'space160',
          'space192',
          'space240',
          'full',
          'auto',
          'fit',
          'min',
          'max',
          'screen',
          'page',
        ],
        description:
          'Maximum width — constrain a form/column so it does not stretch edge-to-edge. Use a container step: space96=384 (small form), space160=640 (content column), space240=960 (wide dashboard).',
      },
      {
        name: 'minHeight',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'space24',
          'space32',
          'space40',
          'space48',
          'space64',
          'space80',
          'space96',
          'space128',
          'space160',
          'space192',
          'space240',
          'full',
          'auto',
          'fit',
          'min',
          'max',
          'screen',
          'page',
        ],
        description: 'Minimum height.',
      },
      {
        name: 'maxHeight',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'space24',
          'space32',
          'space40',
          'space48',
          'space64',
          'space80',
          'space96',
          'space128',
          'space160',
          'space192',
          'space240',
          'full',
          'auto',
          'fit',
          'min',
          'max',
          'screen',
          'page',
        ],
        description: 'Maximum height.',
      },
      {
        name: 'position',
        type: 'enum',
        enum: ['static', 'relative', 'absolute', 'fixed', 'sticky'],
        description: 'CSS position.',
      },
      {
        name: 'inset',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'auto',
          'full',
        ],
        description: 'All inset offsets (space token or keyword).',
      },
      {
        name: 'top',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'auto',
          'full',
        ],
        description: 'Top offset.',
      },
      {
        name: 'right',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'auto',
          'full',
        ],
        description: 'Right offset.',
      },
      {
        name: 'bottom',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'auto',
          'full',
        ],
        description: 'Bottom offset.',
      },
      {
        name: 'left',
        type: 'enum',
        enum: [
          'space0',
          'space1',
          'space2',
          'space3',
          'space4',
          'space5',
          'space6',
          'space8',
          'space10',
          'space12',
          'space16',
          'space20',
          'auto',
          'full',
        ],
        description: 'Left offset.',
      },
      {
        name: 'zIndex',
        type: 'enum',
        enum: [
          'base',
          'sticky',
          'dropdown',
          'overlay',
          'modal',
          'toast',
          'tooltip',
        ],
        description: 'Z-index layer token.',
      },
      {
        name: 'overflow',
        type: 'enum',
        enum: ['visible', 'hidden', 'clip', 'scroll', 'auto'],
        description: 'Overflow on both axes.',
      },
      {
        name: 'overflowX',
        type: 'enum',
        enum: ['visible', 'hidden', 'clip', 'scroll', 'auto'],
        description: 'Horizontal overflow.',
      },
      {
        name: 'overflowY',
        type: 'enum',
        enum: ['visible', 'hidden', 'clip', 'scroll', 'auto'],
        description: 'Vertical overflow.',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'Breadcrumb',
    description:
      'Wayfinding trail; list crumbs as Breadcrumb.Item children, separators auto-inserted.',
    acceptsChildren: true,
    childrenKind: 'nodes',
    props: [
      {
        name: 'aria-label',
        type: 'string',
        description:
          "Accessible label for the nav landmark; defaults to 'Breadcrumb'.",
        required: false,
      },
    ],
    subcomponents: [
      {
        name: 'Breadcrumb.Item',
        description:
          'A single crumb; a link by default, or non-interactive current page when current is set.',
        acceptsChildren: true,
        childrenKind: 'text',
        props: [
          {
            name: 'current',
            type: 'boolean',
            description:
              'Marks the current page; renders as emphasized non-interactive text instead of a link.',
            required: false,
          },
          {
            name: 'href',
            type: 'string',
            description:
              'Destination URL for an ancestor crumb; omit on the current crumb.',
            required: false,
          },
        ],
      },
    ],
  },
  {
    name: 'Button',
    description:
      "Clickable action button; use 'default' for the primary lime action and other variants for lower emphasis or status actions.",
    acceptsChildren: true,
    childrenKind: 'nodes',
    props: [
      {
        name: 'variant',
        type: 'enum',
        enum: [
          'default',
          'subtle',
          'secondary',
          'ghost',
          'success',
          'warning',
          'danger',
        ],
        description: "Visual treatment; 'default' is the lime primary action.",
        required: false,
      },
      {
        name: 'size',
        type: 'enum',
        enum: ['sm', 'md', 'lg'],
        description: 'Control height and type scale.',
        required: false,
      },
      {
        name: 'prefix',
        type: 'node',
        description: 'Icon rendered before the label.',
        required: false,
      },
      {
        name: 'suffix',
        type: 'node',
        description: 'Icon rendered after the label.',
        required: false,
      },
      {
        name: 'loading',
        type: 'boolean',
        description:
          'Shows a leading spinner and makes the button inert while keeping its label.',
        required: false,
      },
      {
        name: 'disabled',
        type: 'boolean',
        description: 'Disables the button (native disabled, greyed out).',
        required: false,
      },
      {
        name: 'type',
        type: 'enum',
        enum: ['button', 'submit', 'reset'],
        description: "Native button type; defaults to 'button'.",
        required: false,
      },
    ],
    subcomponents: [],
  },
  {
    name: 'Card',
    description:
      'A surface container with optional border and rounded corners; compose with Card.Header/Body/Footer. IMPORTANT: the sections carry NO built-in padding — always wrap a section\'s content in a Box that adds padding (Card.Body → Box p="space6"; Card.Header/Footer → Box px="space6" py="space4").',
    acceptsChildren: true,
    childrenKind: 'nodes',
    props: [
      {
        name: 'border',
        type: 'boolean',
        description: 'Hairline outer border. Default true.',
        required: false,
      },
      {
        name: 'radius',
        type: 'enum',
        enum: ['none', 'nav', 'control', 'surface'],
        description: "Corner radius amount. Default 'surface' (12px).",
        required: false,
      },
      {
        name: 'width',
        type: 'enum',
        enum: ['full', 'fit', 'auto'],
        description: 'Width behavior; fills the container by default.',
        required: false,
      },
    ],
    subcomponents: [
      {
        name: 'Card.Header',
        description: 'Top bar of the card for titles or actions.',
        acceptsChildren: true,
        childrenKind: 'nodes',
        props: [
          {
            name: 'background',
            type: 'enum',
            enum: ['none', 'subtle'],
            description: "Section fill; 'none' is transparent. Default 'none'.",
          },
          {
            name: 'shadow',
            type: 'boolean',
            description:
              'Cast a soft shadow onto the body (raised/sticky look). Default false.',
          },
        ],
      },
      {
        name: 'Card.Body',
        description: 'Main content region of the card.',
        acceptsChildren: true,
        childrenKind: 'nodes',
        props: [
          {
            name: 'background',
            type: 'enum',
            enum: ['none', 'subtle'],
            description: "Section fill; 'none' is transparent. Default 'none'.",
          },
        ],
      },
      {
        name: 'Card.Footer',
        description: 'Bottom bar of the card for actions or summary content.',
        acceptsChildren: true,
        childrenKind: 'nodes',
        props: [
          {
            name: 'background',
            type: 'enum',
            enum: ['none', 'subtle'],
            description: "Section fill; 'none' is transparent. Default 'none'.",
          },
          {
            name: 'shadow',
            type: 'boolean',
            description:
              'Cast a soft shadow onto the body (raised/sticky look). Default false.',
          },
        ],
      },
    ],
  },
  {
    name: 'Checkbox',
    description:
      'A toggleable checkbox with optional label; use for boolean on/off selections in forms.',
    acceptsChildren: false,
    childrenKind: 'none',
    props: [
      {
        name: 'label',
        type: 'node',
        required: false,
        description:
          'Optional text/content beside the box; clicking it toggles the checkbox.',
      },
      {
        name: 'color',
        type: 'enum',
        enum: ['default', 'success'],
        required: false,
        description:
          'Checked-state fill color (default = obsidian/charcoal, success = green).',
      },
      {
        name: 'size',
        type: 'enum',
        enum: ['sm', 'md'],
        required: false,
        description:
          'Control size; box, tick, label and gap scale together (default md).',
      },
      {
        name: 'defaultChecked',
        type: 'boolean',
        required: false,
        description: 'Initial checked state for an uncontrolled checkbox.',
      },
      {
        name: 'checked',
        type: 'boolean',
        required: false,
        description: 'Controlled checked state.',
      },
      {
        name: 'indeterminate',
        type: 'boolean',
        required: false,
        description: 'Renders the mixed/indeterminate state.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        required: false,
        description: 'Disables interaction and dims the control.',
      },
      {
        name: 'name',
        type: 'string',
        required: false,
        description: 'Form field name submitted with the form.',
      },
      {
        name: 'value',
        type: 'string',
        required: false,
        description: 'Value submitted when the checkbox is checked.',
      },
      {
        name: 'required',
        type: 'boolean',
        required: false,
        description: 'Marks the field as required in a form.',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'CommandMenu',
    description:
      'A ⌘K command palette: a searchable, grouped list of actions. In this builder it renders as a trigger button that opens the palette (it is a controlled overlay, so you only supply its contents). Use for command palettes or quick-action search.',
    acceptsChildren: false,
    childrenKind: 'none',
    props: [
      {
        name: 'groups',
        type: 'other',
        required: true,
        description:
          'Array of groups, each { heading: string, items: [{ id: string, label: string, icon?: "<LucideName>", keywords?: string[] }] }. icon is a lucide-react name string; do NOT add onSelect — the builder wires selection for you.',
      },
      {
        name: 'placeholder',
        type: 'string',
        required: false,
        description: "Search input placeholder. Default 'Search…'.",
      },
      {
        name: 'emptyMessage',
        type: 'string',
        required: false,
        description: "Shown when nothing matches the query. Default 'No results.'.",
      },
    ],
    subcomponents: [],
  },
  {
    name: 'CopyButton',
    description:
      'An icon button that copies a text value to the clipboard and confirms with a copy → check swap. Hand it the text and it owns the whole interaction.',
    acceptsChildren: false,
    childrenKind: 'none',
    props: [
      {
        name: 'value',
        type: 'string',
        required: true,
        description: 'The text written to the clipboard on click.',
      },
      {
        name: 'variant',
        type: 'enum',
        enum: [
          'default',
          'subtle',
          'secondary',
          'ghost',
          'success',
          'warning',
          'danger',
        ],
        required: false,
        description: 'Visual treatment (inherited from IconButton). Default secondary.',
      },
      {
        name: 'size',
        type: 'enum',
        enum: ['sm', 'md', 'lg'],
        required: false,
        description: 'Control footprint and icon scale. Default md.',
      },
      {
        name: 'shape',
        type: 'enum',
        enum: ['square', 'circle'],
        required: false,
        description:
          'Corner geometry: square keeps the family radius, circle is fully round.',
      },
      {
        name: 'aria-label',
        type: 'string',
        required: false,
        description: "Accessible name for the idle state. Default 'Copy'.",
      },
      {
        name: 'copiedLabel',
        type: 'string',
        required: false,
        description: "Accessible name announced once copied. Default 'Copied'.",
      },
      {
        name: 'disabled',
        type: 'boolean',
        required: false,
        description: 'Disables the button.',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'FormInput',
    description:
      'A large floating-label text input with optional trailing icon, helper text, and error state.',
    acceptsChildren: false,
    childrenKind: 'none',
    props: [
      {
        name: 'label',
        type: 'string',
        required: true,
        description:
          'Floating label inside the field; serves as the accessible name (no separate placeholder).',
      },
      {
        name: 'endIcon',
        type: 'node',
        required: false,
        description:
          'Decorative trailing (right) icon, e.g. a Lucide element; auto-sized to the control.',
      },
      {
        name: 'description',
        type: 'node',
        required: false,
        description:
          'Helper line below the field; hidden while an error is showing.',
      },
      {
        name: 'error',
        type: 'node',
        required: false,
        description:
          'Error message; when set the field reads as invalid and replaces the description.',
      },
      {
        name: 'defaultValue',
        type: 'string',
        required: false,
        description:
          'Initial value for an uncontrolled input (sets the filled/floated state).',
      },
      {
        name: 'value',
        type: 'string',
        required: false,
        description: 'Controlled value of the input.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        required: false,
        description: 'Disables the input.',
      },
      {
        name: 'required',
        type: 'boolean',
        required: false,
        description: 'Marks the input as required.',
      },
      {
        name: 'type',
        type: 'string',
        required: false,
        description:
          'Native input type, e.g. text, email, password, number, tel, url.',
      },
      {
        name: 'name',
        type: 'string',
        required: false,
        description: 'Form field name for submission.',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'IconButton',
    description:
      'Icon-only button for compact actions; renders a single icon and requires an aria-label.',
    acceptsChildren: true,
    childrenKind: 'nodes',
    props: [
      {
        name: 'variant',
        type: 'enum',
        enum: [
          'default',
          'subtle',
          'secondary',
          'ghost',
          'success',
          'warning',
          'danger',
        ],
        description: 'Visual treatment; default is the lime primary action.',
      },
      {
        name: 'size',
        type: 'enum',
        enum: ['sm', 'md', 'lg'],
        description: 'Control footprint and icon scale.',
      },
      {
        name: 'shape',
        type: 'enum',
        enum: ['square', 'circle'],
        description:
          'Corner geometry: square keeps family radius, circle is fully round.',
      },
      {
        name: 'aria-label',
        type: 'string',
        required: true,
        description:
          'Accessible name; required since there is no visible label.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        description: 'Disables the button.',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'Input',
    description:
      'Single-line text field with optional label, prefix/suffix slots, description, and error state.',
    acceptsChildren: false,
    childrenKind: 'none',
    props: [
      {
        name: 'label',
        type: 'string',
        description: 'Optional label rendered above the field.',
      },
      {
        name: 'size',
        type: 'enum',
        enum: ['sm', 'md', 'lg'],
        description: 'Control size; height and text scale together.',
      },
      {
        name: 'placeholder',
        type: 'string',
        description: 'Native placeholder text shown when empty.',
      },
      {
        name: 'prefix',
        type: 'node',
        description:
          "Leading slot (left): a Lucide icon or short text like '$'.",
      },
      {
        name: 'suffix',
        type: 'node',
        description:
          "Trailing slot (right): a Lucide icon or short text like 'USD'.",
      },
      {
        name: 'description',
        type: 'node',
        description:
          'Helper line below the field; hidden while an error is showing.',
      },
      {
        name: 'error',
        type: 'node',
        description:
          'Error message; marks field invalid and replaces description.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        description: 'Disables the field.',
      },
      {
        name: 'defaultValue',
        type: 'string',
        description: 'Initial uncontrolled value of the field.',
      },
      {
        name: 'value',
        type: 'string',
        description: 'Controlled value of the field.',
      },
      {
        name: 'type',
        type: 'string',
        description: 'Native input type (text, email, password, number, etc.).',
      },
      {
        name: 'required',
        type: 'boolean',
        description: 'Marks the field as required.',
      },
      {
        name: 'readOnly',
        type: 'boolean',
        description: 'Makes the field read-only.',
      },
      {
        name: 'name',
        type: 'string',
        description: 'Form field name for submission.',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'LinkButton',
    description:
      'A button-styled link for navigation; renders an <a>, use when the action navigates somewhere.',
    acceptsChildren: true,
    childrenKind: 'nodes',
    props: [
      {
        name: 'href',
        type: 'string',
        description: 'Destination URL the link navigates to.',
      },
      {
        name: 'variant',
        type: 'enum',
        enum: [
          'default',
          'subtle',
          'secondary',
          'ghost',
          'success',
          'warning',
          'danger',
        ],
        description: "Visual treatment; 'default' is the lime primary action.",
        required: false,
      },
      {
        name: 'size',
        type: 'enum',
        enum: ['sm', 'md', 'lg'],
        description: 'Control height and type scale.',
        required: false,
      },
      {
        name: 'prefix',
        type: 'node',
        description: 'Icon rendered before the label.',
        required: false,
      },
      {
        name: 'suffix',
        type: 'node',
        description: 'Icon rendered after the label.',
        required: false,
      },
    ],
    subcomponents: [],
  },
  {
    name: 'Logo',
    description:
      'The Ramp brand logo — the mark (swoosh isotype) or the full wordmark, as an inline currentColor SVG. Use in app headers/footers or as a brand accent.',
    acceptsChildren: false,
    childrenKind: 'none',
    props: [
      {
        name: 'type',
        type: 'enum',
        enum: ['mark', 'wordmark'],
        required: false,
        description:
          "Which lockup: 'mark' (swoosh symbol only) or 'wordmark' (full ramp logotype). Default mark.",
      },
      {
        name: 'size',
        type: 'enum',
        enum: ['xs', 'sm', 'md'],
        required: false,
        description: 'Height: xs=16px, sm=24px, md=32px. Default sm.',
      },
      {
        name: 'tone',
        type: 'enum',
        enum: ['default', 'muted', 'inverse'],
        required: false,
        description:
          'Colour: default (dark), muted (grey), inverse (white, for dark surfaces). Default default.',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'Menu',
    description:
      'Dropdown menu triggered by a button; compose with dot-subcomponents for items and sections.',
    acceptsChildren: true,
    childrenKind: 'nodes',
    props: [
      {
        name: 'defaultOpen',
        type: 'boolean',
        description: 'Uncontrolled initial open state.',
        required: false,
      },
      {
        name: 'open',
        type: 'boolean',
        description: 'Controlled open state.',
        required: false,
      },
      {
        name: 'modal',
        type: 'boolean',
        description:
          'Scroll-lock and outside-interaction guard (default true).',
        required: false,
      },
    ],
    subcomponents: [
      {
        name: 'Menu.Trigger',
        description:
          'The element that opens the menu; defaults to a secondary Button when given text children.',
        acceptsChildren: true,
        childrenKind: 'nodes',
        props: [],
      },
      {
        name: 'Menu.Content',
        description:
          'The dropdown panel that holds menu items; wraps all Items/Sections.',
        acceptsChildren: true,
        childrenKind: 'nodes',
        props: [
          {
            name: 'side',
            type: 'enum',
            enum: ['top', 'bottom', 'left', 'right'],
            description: 'Side of the trigger to anchor to (default bottom).',
            required: false,
          },
          {
            name: 'align',
            type: 'enum',
            enum: ['start', 'center', 'end'],
            description: 'Alignment along the chosen side (default start).',
            required: false,
          },
          {
            name: 'sideOffset',
            type: 'number',
            description: 'Gap between trigger and panel in px (default 6).',
            required: false,
          },
        ],
      },
      {
        name: 'Menu.Item',
        description:
          'A clickable menu action row with optional icons and destructive/disabled states.',
        acceptsChildren: true,
        childrenKind: 'text',
        props: [
          {
            name: 'prefix',
            type: 'node',
            description: 'Leading icon (auto-sized).',
            required: false,
          },
          {
            name: 'suffix',
            type: 'node',
            description: 'Trailing icon (auto-sized).',
            required: false,
          },
          {
            name: 'disabled',
            type: 'boolean',
            description: 'Ignore interaction and mute the row.',
            required: false,
          },
          {
            name: 'destructive',
            type: 'boolean',
            description: 'Danger styling for destructive actions.',
            required: false,
          },
          {
            name: 'closeOnClick',
            type: 'boolean',
            description: 'Close the menu on click (default true).',
            required: false,
          },
        ],
      },
      {
        name: 'Menu.LinkItem',
        description:
          'A menu row rendered as an anchor that navigates to an href.',
        acceptsChildren: true,
        childrenKind: 'text',
        props: [
          {
            name: 'href',
            type: 'string',
            description: 'Destination URL for the link.',
            required: true,
          },
          {
            name: 'prefix',
            type: 'node',
            description: 'Leading icon (auto-sized).',
            required: false,
          },
          {
            name: 'suffix',
            type: 'node',
            description: 'Trailing icon (auto-sized).',
            required: false,
          },
          {
            name: 'disabled',
            type: 'boolean',
            description: 'Ignore interaction and mute the row.',
            required: false,
          },
        ],
      },
      {
        name: 'Menu.Section',
        description: 'A labeled group of menu items.',
        acceptsChildren: true,
        childrenKind: 'nodes',
        props: [
          {
            name: 'label',
            type: 'string',
            description: 'Section heading text.',
            required: true,
          },
        ],
      },
      {
        name: 'Menu.Separator',
        description: 'A horizontal divider between menu items or sections.',
        acceptsChildren: false,
        childrenKind: 'none',
        props: [],
      },
      {
        name: 'Menu.Chevron',
        description:
          'A down-chevron icon for a trigger that rotates with the open state.',
        acceptsChildren: false,
        childrenKind: 'none',
        props: [],
      },
    ],
  },
  {
    name: 'Modal',
    description:
      'A centered dialog over a scrim for confirmations, forms, or focused content; control open from state.',
    acceptsChildren: true,
    childrenKind: 'nodes',
    props: [
      {
        name: 'title',
        type: 'node',
        required: true,
        description: "Header title; also sets the dialog's accessible name.",
      },
      {
        name: 'footer',
        type: 'node',
        required: false,
        description: 'Optional footer slot for actions like Cancel / Confirm.',
      },
      {
        name: 'defaultOpen',
        type: 'boolean',
        required: false,
        description: 'Initial open state for an uncontrolled modal.',
      },
      {
        name: 'open',
        type: 'boolean',
        required: false,
        description: 'Controlled open state.',
      },
      {
        name: 'dismissible',
        type: 'boolean',
        required: false,
        description:
          'When false, backdrop click and Esc no longer close the modal (default true).',
      },
      {
        name: 'showClose',
        type: 'boolean',
        required: false,
        description: 'Show the built-in close X button (default true).',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'Pill',
    description:
      'Interactive chip — the clickable twin of Badge (same pill look, on a button). Use for selectable/removable chips, filters, or starter suggestions; use Badge for non-interactive status display.',
    acceptsChildren: true,
    childrenKind: 'nodes',
    props: [
      {
        name: 'status',
        type: 'enum',
        enum: ['neutral', 'success', 'warning', 'error', 'info'],
        required: false,
        description:
          'Selects surface and accent colour; the status hue tints the icon only. Default neutral.',
      },
      {
        name: 'size',
        type: 'enum',
        enum: ['sm', 'md'],
        required: false,
        description: 'Density scale; default md.',
      },
      {
        name: 'icon',
        type: 'node',
        required: false,
        description:
          'Optional leading Lucide icon, auto-sized and tinted by status.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        required: false,
        description: 'Disables the chip (native disabled).',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'SearchInput',
    description:
      'Fully-rounded search field with leading magnifier, loading spinner, and a ⌘K focus-hint chip.',
    acceptsChildren: false,
    childrenKind: 'none',
    props: [
      {
        name: 'size',
        type: 'enum',
        enum: ['sm', 'md', 'lg'],
        required: false,
        description: 'Control size (height + text scale together). Default md.',
      },
      {
        name: 'loading',
        type: 'boolean',
        required: false,
        description:
          'Async state: swaps the magnifier for a Spinner and hides the ⌘K chip. Default false.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        required: false,
        description: 'Disables the field and the global ⌘K focus shortcut.',
      },
      {
        name: 'placeholder',
        type: 'string',
        required: false,
        description: "Placeholder text shown when empty. Default 'Search'.",
      },
      {
        name: 'defaultValue',
        type: 'string',
        required: false,
        description: 'Initial value for an uncontrolled field.',
      },
      {
        name: 'value',
        type: 'string',
        required: false,
        description: 'Controlled input value.',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'Select',
    description:
      'Use for a single-choice rectangular dropdown (the standard select).',
    acceptsChildren: false,
    childrenKind: 'none',
    props: [
      {
        name: 'options',
        type: 'options',
        required: true,
        description:
          'Choices in render order; each {value, label, icon?, disabled?}.',
      },
      {
        name: 'size',
        type: 'enum',
        enum: ['sm', 'md'],
        description: "Density: sm=32px, md=36px. Default 'md'.",
      },
      {
        name: 'placeholder',
        type: 'string',
        description: 'Empty-state muted placeholder text.',
      },
      {
        name: 'icon',
        type: 'node',
        description:
          "Leading icon; swaps to the selected option's icon once chosen.",
      },
      {
        name: 'disabled',
        type: 'boolean',
        description: 'Disable the whole control.',
      },
      {
        name: 'defaultValue',
        type: 'string',
        description:
          'Uncontrolled initial selected value (null = nothing selected).',
      },
      {
        name: 'defaultOpen',
        type: 'boolean',
        description: 'Whether the dropdown starts open. Default false.',
      },
      {
        name: 'side',
        type: 'enum',
        enum: ['top', 'bottom', 'left', 'right'],
        description: "Dropdown placement side. Default 'bottom'.",
      },
      {
        name: 'align',
        type: 'enum',
        enum: ['start', 'center', 'end'],
        description: "Dropdown alignment. Default 'start'.",
      },
      {
        name: 'name',
        type: 'string',
        description: 'Form field name.',
      },
      {
        name: 'aria-label',
        type: 'string',
        description: 'Accessible label when no visible label exists.',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'MultiSelect',
    description:
      'Use for a rounded filter pill holding multiple selections shown as pills.',
    acceptsChildren: false,
    childrenKind: 'none',
    props: [
      {
        name: 'options',
        type: 'options',
        required: true,
        description:
          'Choices in render order; each {value, label, icon?, disabled?}.',
      },
      {
        name: 'size',
        type: 'enum',
        enum: ['sm', 'md'],
        description: "Density: sm=32px, md=36px. Default 'md'.",
      },
      {
        name: 'placeholder',
        type: 'string',
        description: 'Empty-state placeholder doubling as the filter name.',
      },
      {
        name: 'icon',
        type: 'node',
        description: 'Fixed leading icon (does not swap with selection).',
      },
      {
        name: 'disabled',
        type: 'boolean',
        description: 'Disable the whole control.',
      },
      {
        name: 'defaultValue',
        type: 'other',
        description: 'Uncontrolled initial selected values (array of strings).',
      },
      {
        name: 'maxVisiblePills',
        type: 'number',
        description:
          "Pills shown before collapsing into a '+N' chip. Default 2.",
      },
      {
        name: 'defaultOpen',
        type: 'boolean',
        description: 'Whether the dropdown starts open. Default false.',
      },
      {
        name: 'side',
        type: 'enum',
        enum: ['top', 'bottom', 'left', 'right'],
        description: "Dropdown placement side. Default 'bottom'.",
      },
      {
        name: 'align',
        type: 'enum',
        enum: ['start', 'center', 'end'],
        description: "Dropdown alignment. Default 'start'.",
      },
      {
        name: 'name',
        type: 'string',
        description: 'Form field name.',
      },
      {
        name: 'aria-label',
        type: 'string',
        description: 'Accessible label when no visible label exists.',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'Separator',
    description:
      'A dividing line between sections of content; use horizontal in columns, vertical in flex rows.',
    acceptsChildren: false,
    childrenKind: 'none',
    props: [
      {
        name: 'orientation',
        type: 'enum',
        enum: ['horizontal', 'vertical'],
        required: false,
        description:
          "Line direction; horizontal (default) for stacked content, vertical to fill a flex row's height.",
      },
    ],
    subcomponents: [],
  },
  {
    name: 'ShimmerText',
    description:
      'Display-only text with a subtle light sheen sweeping across solid obsidian; use for animated emphasis on a short label or heading.',
    acceptsChildren: true,
    childrenKind: 'text',
    props: [
      {
        name: 'as',
        type: 'string',
        description:
          "HTML element to render as (e.g. span, p, h1, strong). Default 'span' (inline).",
        required: false,
      },
      {
        name: 'size',
        type: 'enum',
        description:
          "Typography role applying paired fontSize and lineHeight. Default 'body'.",
        enum: [
          'footnote',
          'caption',
          'body',
          'subheading',
          'heading',
          'headingLg',
        ],
        required: false,
      },
    ],
    subcomponents: [],
  },
  {
    name: 'Skeleton',
    description:
      'Decorative loading placeholder shown while content is being fetched.',
    acceptsChildren: false,
    childrenKind: 'none',
    props: [
      {
        name: 'variant',
        type: 'enum',
        enum: ['text', 'circle', 'rect'],
        description:
          'Shape preset; text is a line/stacked lines, circle and rect are blocks. Default text.',
        required: false,
      },
      {
        name: 'lines',
        type: 'number',
        description:
          'Number of stacked bars (text variant only); last bar is shortened. Default 1.',
        required: false,
      },
      {
        name: 'size',
        type: 'enum',
        enum: ['sm', 'md', 'lg'],
        description: 'Circle diameter (circle variant only). Default md.',
        required: false,
      },
    ],
    subcomponents: [],
  },
  {
    name: 'Spinner',
    description:
      'Loading indicator (animated arc) for inline or in-control busy states.',
    acceptsChildren: false,
    childrenKind: 'none',
    props: [
      {
        name: 'size',
        type: 'enum',
        enum: ['sm', 'md', 'lg'],
        required: false,
        description: 'Diameter on the control scale. Default md (14px).',
      },
      {
        name: 'tone',
        type: 'enum',
        enum: ['default', 'inherit'],
        required: false,
        description:
          'default paints the arc charcoal; inherit rides parent currentColor. Default default.',
      },
      {
        name: 'label',
        type: 'string',
        required: false,
        description:
          "Accessible label announced via role=status. Default 'Loading'.",
      },
    ],
    subcomponents: [],
  },
  {
    name: 'StackLogo',
    description:
      'The Stack brand mark (hexagonal honeycomb of 7 dots); use as a logo or, with loading, as a spinner.',
    acceptsChildren: false,
    childrenKind: 'none',
    props: [
      {
        name: 'size',
        type: 'enum',
        enum: ['xs', 'sm', 'md'],
        required: false,
        description: 'Box size: xs=16px, sm=24px, md=32px (default md).',
      },
      {
        name: 'loading',
        type: 'boolean',
        required: false,
        description:
          'true makes the mark wobble as a loading status indicator; default false (static).',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'Switch',
    description:
      'Toggle for a single on/off boolean setting; on state is always green.',
    acceptsChildren: false,
    childrenKind: 'none',
    props: [
      {
        name: 'label',
        type: 'node',
        description:
          'Optional text shown beside the switch; clicking it toggles.',
      },
      {
        name: 'size',
        type: 'enum',
        enum: ['sm', 'md'],
        description:
          'Control size; track, knob, label and gap scale together. Default md.',
      },
      {
        name: 'defaultChecked',
        type: 'boolean',
        description:
          'Whether the switch is initially on (uncontrolled). Use for default checked state.',
      },
      {
        name: 'checked',
        type: 'boolean',
        description: 'Controlled on/off state.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        description: 'Disable user interaction. Default false.',
      },
      {
        name: 'readOnly',
        type: 'boolean',
        description: 'Prevent the user from changing the value. Default false.',
      },
      {
        name: 'required',
        type: 'boolean',
        description: 'Require activation before form submit. Default false.',
      },
      {
        name: 'name',
        type: 'string',
        description: 'Field name used when submitted in a form.',
      },
      {
        name: 'value',
        type: 'string',
        description: 'Value submitted with the form when the switch is on.',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'Table',
    description: 'Compound data table for displaying rows and columns of data.',
    acceptsChildren: true,
    childrenKind: 'nodes',
    props: [
      {
        name: 'striped',
        type: 'boolean',
        description: 'Tint even body rows with a faint band. Default false.',
      },
      {
        name: 'hover',
        type: 'boolean',
        description: 'Highlight a body row on hover. Default false.',
      },
      {
        name: 'bordered',
        type: 'boolean',
        description:
          'Add outer box plus vertical column dividers (full grid). Default false.',
      },
    ],
    subcomponents: [
      {
        name: 'Table.Head',
        description: 'Table header section wrapping the header row(s).',
        acceptsChildren: true,
        childrenKind: 'nodes',
        props: [],
      },
      {
        name: 'Table.Body',
        description: 'Table body section wrapping the data rows.',
        acceptsChildren: true,
        childrenKind: 'nodes',
        props: [],
      },
      {
        name: 'Table.Row',
        description: 'A table row containing header or data cells.',
        acceptsChildren: true,
        childrenKind: 'nodes',
        props: [],
      },
      {
        name: 'Table.HeaderCell',
        description: 'Column header cell; use inside Table.Head rows.',
        acceptsChildren: true,
        childrenKind: 'nodes',
        props: [
          {
            name: 'align',
            type: 'enum',
            enum: ['left', 'center', 'right'],
            description:
              'Text alignment; pair right with numbers. Default left.',
          },
        ],
      },
      {
        name: 'Table.Cell',
        description: 'Data cell; use inside Table.Body rows.',
        acceptsChildren: true,
        childrenKind: 'nodes',
        props: [
          {
            name: 'align',
            type: 'enum',
            enum: ['left', 'center', 'right'],
            description:
              'Text alignment; pair right with numbers. Default left.',
          },
        ],
      },
    ],
  },
  {
    name: 'Tabs',
    description:
      'Compound tabbed interface: groups a tab strip and its panels and owns the active tab.',
    acceptsChildren: true,
    childrenKind: 'nodes',
    props: [
      {
        name: 'defaultValue',
        type: 'other',
        description:
          'Uncontrolled initial active tab value; matches a Tab/Panel value (defaults to 0).',
      },
      {
        name: 'value',
        type: 'other',
        description:
          'Controlled active tab value; matches a Tab/Panel value (null = none active).',
      },
      {
        name: 'orientation',
        type: 'enum',
        enum: ['horizontal', 'vertical'],
        description:
          "Layout flow direction of the tab strip (default 'horizontal').",
      },
    ],
    subcomponents: [
      {
        name: 'Tabs.List',
        description:
          'The tab strip; wraps the Tab buttons and renders the sliding underline indicator automatically.',
        acceptsChildren: true,
        childrenKind: 'nodes',
        props: [
          {
            name: 'activateOnFocus',
            type: 'boolean',
            description:
              'Activate a tab on arrow-key focus instead of on Enter/Space (default false).',
          },
          {
            name: 'loopFocus',
            type: 'boolean',
            description:
              'Loop keyboard focus from last tab back to first (default true).',
          },
        ],
      },
      {
        name: 'Tabs.Tab',
        description:
          'A single clickable tab button; its value ties it to the matching Tabs.Panel.',
        acceptsChildren: true,
        childrenKind: 'nodes',
        props: [
          {
            name: 'value',
            type: 'other',
            required: true,
            description: 'Identifier linking this tab to its Tabs.Panel.',
          },
          {
            name: 'disabled',
            type: 'boolean',
            description: 'Disables the tab button so it cannot be activated.',
          },
        ],
      },
      {
        name: 'Tabs.Panel',
        description:
          'Content shown when the tab with the matching value is active; optional for nav-only tabs.',
        acceptsChildren: true,
        childrenKind: 'nodes',
        props: [
          {
            name: 'value',
            type: 'other',
            required: true,
            description: 'Identifier linking this panel to its Tabs.Tab.',
          },
          {
            name: 'keepMounted',
            type: 'boolean',
            description:
              'Keep the panel in the DOM while hidden (default false).',
          },
        ],
      },
    ],
  },
  {
    name: 'Text',
    description:
      'Display typography primitive for rendering styled text with a typographic role and tone.',
    acceptsChildren: true,
    childrenKind: 'nodes',
    props: [
      {
        name: 'as',
        type: 'string',
        description:
          "Element to render as (e.g. 'span','p','h1','label','strong'); default 'span'.",
      },
      {
        name: 'size',
        type: 'enum',
        enum: [
          'footnote',
          'caption',
          'body',
          'subheading',
          'heading',
          'headingLg',
        ],
        description:
          "Typography role applying paired fontSize + lineHeight; default 'body'.",
      },
      {
        name: 'tone',
        type: 'enum',
        enum: ['primary', 'secondary', 'tertiary'],
        description: "Foreground tone; default 'primary'.",
      },
    ],
    subcomponents: [],
  },
  {
    name: 'Textarea',
    description:
      'Multi-line text input that auto-grows to fit content; use for longer free-form text entry with optional label, description, or error.',
    acceptsChildren: false,
    childrenKind: 'none',
    props: [
      {
        name: 'label',
        type: 'string',
        description: 'Label rendered above the field.',
      },
      {
        name: 'description',
        type: 'node',
        description:
          'Helper line below the field; hidden when an error is showing.',
      },
      {
        name: 'error',
        type: 'node',
        description:
          'Error message; marks the field invalid and replaces the description.',
      },
      {
        name: 'seamless',
        type: 'boolean',
        description:
          'Strip border, background, focus ring and padding for a bare typing area.',
      },
      {
        name: 'placeholder',
        type: 'string',
        description: 'Placeholder text shown when empty.',
      },
      {
        name: 'defaultValue',
        type: 'string',
        description: 'Initial uncontrolled text value.',
      },
      {
        name: 'value',
        type: 'string',
        description: 'Controlled text value.',
      },
      {
        name: 'rows',
        type: 'number',
        description: 'Fixed N-row height; disables auto-grow when set.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        description: 'Disable the field.',
      },
      {
        name: 'required',
        type: 'boolean',
        description: 'Mark the field as required.',
      },
      {
        name: 'readOnly',
        type: 'boolean',
        description: 'Make the field read-only.',
      },
      {
        name: 'name',
        type: 'string',
        description: 'Form field name.',
      },
      {
        name: 'maxLength',
        type: 'number',
        description: 'Maximum number of characters allowed.',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'Timeline',
    description:
      'Use to show ordered steps on a vertical dotted rail where each step is a collapsible row; the last step is the current one.',
    acceptsChildren: true,
    childrenKind: 'nodes',
    props: [
      {
        name: 'loading',
        type: 'boolean',
        description:
          'Whole timeline is working; the current (last) dot bounces and that step reads as in-progress. Default false.',
      },
      {
        name: 'multiple',
        type: 'boolean',
        description:
          'Whether multiple steps can be open at once. Default true.',
      },
      {
        name: 'defaultValue',
        type: 'other',
        description:
          'Uncontrolled initial open step values: array of string|number.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        description: 'Disable the whole timeline.',
      },
    ],
    subcomponents: [
      {
        name: 'Timeline.Item',
        description:
          'A single step in the timeline; its title is the trigger and children are the panel body revealed when open.',
        acceptsChildren: true,
        childrenKind: 'nodes',
        props: [
          {
            name: 'title',
            type: 'node',
            required: true,
            description: 'The step label shown as the accordion trigger.',
          },
          {
            name: 'value',
            type: 'other',
            description:
              'Stable identity (string|number) for controlled open state; defaults to the step index.',
          },
          {
            name: 'disabled',
            type: 'boolean',
            description: 'Disable just this step.',
          },
        ],
      },
    ],
  },
  {
    name: 'ToggleGroup',
    description:
      'Icon-only single-select segmented control where exactly one option is always active.',
    acceptsChildren: false,
    childrenKind: 'none',
    props: [
      {
        name: 'items',
        type: 'options',
        required: true,
        description:
          "The options left to right; each is {value, icon (Lucide component), 'aria-label', disabled?}. Drives the control.",
      },
      {
        name: 'size',
        type: 'enum',
        enum: ['md', 'lg'],
        required: false,
        description: 'Density: md (32px tall) or lg (36px tall). Default md.',
      },
      {
        name: 'defaultValue',
        type: 'string',
        required: false,
        description:
          "Uncontrolled initial selected value; matches an item's value. Defaults to first item.",
      },
      {
        name: 'value',
        type: 'string',
        required: false,
        description: 'Controlled selected value (single).',
      },
      {
        name: 'disabled',
        type: 'boolean',
        required: false,
        description: 'Disable the whole control. Default false.',
      },
      {
        name: 'aria-label',
        type: 'string',
        required: false,
        description: 'Accessible name for the group.',
      },
      {
        name: 'aria-labelledby',
        type: 'string',
        required: false,
        description:
          'Accessible name by reference (alternative to aria-label).',
      },
    ],
    subcomponents: [],
  },
  {
    name: 'UserMessage',
    description:
      'A single outgoing (user) chat message rendered as a right-hugging bubble with an optional date/time footnote below.',
    acceptsChildren: true,
    childrenKind: 'nodes',
    props: [
      {
        name: 'date',
        type: 'string',
        required: false,
        description:
          "Pre-formatted date shown beneath the bubble, e.g. 'Jun 23'. No locale formatting is applied.",
      },
      {
        name: 'time',
        type: 'string',
        required: false,
        description:
          "Pre-formatted time shown beneath the bubble, e.g. '2:45 PM'. Joined to date with a middot when both are present.",
      },
      {
        name: 'as',
        type: 'other',
        required: false,
        description:
          "The element/tag the message renders as. Default 'div'; pass 'li', 'article', etc.",
      },
    ],
    subcomponents: [],
  },
];
