// playground/scripts/gen-docs.mjs
// AUTO-GENERATES playground/src/generated/{components.manifest.ts,docs.generated.ts}
// from ken/components/*/doc.md. Wired as predev/prebuild and `pnpm gen:docs`.
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import fg from 'fast-glob';
import matter from 'gray-matter';

const require = createRequire(import.meta.url);
const docgen = require('react-docgen-typescript');

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..', '..');
const kenComponents = join(repoRoot, 'ken', 'components');
const outDir = join(here, '..', 'src', 'generated');
const tsconfig = join(repoRoot, 'ken', 'tsconfig.json');

const parser = docgen.withCustomConfig(tsconfig, {
  savePropValueAsString: true,
  shouldExtractLiteralValuesFromEnum: true,
  shouldRemoveUndefinedFromOptional: true,
  // Keep props declared in the component's own file; drop inherited DOM/Base UI
  // props (those resolve to node_modules / @types parents).
  propFilter: (prop) => !prop.parent?.fileName.includes('node_modules'),
});

function extractProps(componentFile, displayName) {
  if (!existsSync(componentFile)) {
    console.warn(
      `gen-docs: no component file for "${displayName}" at ${componentFile} — props omitted`,
    );
    return [];
  }
  let docs = [];
  try {
    docs = parser.parse(componentFile);
  } catch (e) {
    console.warn(
      `gen-docs: react-docgen failed on ${componentFile}: ${e.message} — props omitted`,
    );
    return [];
  }
  const doc = docs.find((d) => d.displayName === displayName) ?? docs[0];
  if (!doc) {
    console.warn(
      `gen-docs: react-docgen found no component matching "${displayName}" in ${componentFile} — props omitted`,
    );
    return [];
  }
  return Object.values(doc.props).map((p) => ({
    name: p.name,
    type: p.type?.name || '',
    required: !!p.required,
    defaultValue: p.defaultValue ? String(p.defaultValue.value) : null,
    description: p.description || '',
  }));
}

const files = fg.sync('*/doc.md', { cwd: kenComponents }).sort();
const entries = [];
for (const rel of files) {
  const folder = rel.split('/')[0];
  const { data, content } = matter(
    readFileSync(join(kenComponents, rel), 'utf8'),
  );
  for (const k of ['title', 'component', 'description']) {
    if (!data[k])
      throw new Error(
        `doc.md for ${folder} is missing required frontmatter "${k}"`,
      );
  }
  const props = extractProps(
    join(kenComponents, folder, `${folder}.tsx`),
    data.component,
  );
  entries.push({
    meta: {
      slug: folder.toLowerCase(),
      title: data.title,
      description: data.description,
      component: data.component,
      status: data.status ?? null,
      category: data.category ?? null,
      // Optional hero image (public path, e.g. /ken-media/x.png) shown above the
      // doc body. Omit it and the page renders without one.
      hero: data.hero ?? null,
    },
    body: content.trim(),
    props,
  });
}

entries.sort((a, b) => a.meta.title.localeCompare(b.meta.title));
mkdirSync(outDir, { recursive: true });

const HEADER = '// AUTO-GENERATED by scripts/gen-docs.mjs — DO NOT EDIT.\n';

writeFileSync(
  join(outDir, 'components.manifest.ts'),
  HEADER +
    'export interface ComponentMeta {\n' +
    '  slug: string; title: string; description: string;\n' +
    '  component: string; status: string | null; category: string | null;\n' +
    '  hero: string | null;\n' +
    '}\n' +
    `export const COMPONENTS: ComponentMeta[] = ${JSON.stringify(
      entries.map((e) => e.meta),
      null,
      2,
    )};\n`,
);

writeFileSync(
  join(outDir, 'docs.generated.ts'),
  HEADER +
    "import type { ComponentMeta } from './components.manifest';\n" +
    'export interface PropDoc { name: string; type: string; required: boolean; defaultValue: string | null; description: string; }\n' +
    'export interface DocEntry { meta: ComponentMeta; body: string; props: PropDoc[]; }\n' +
    `export const DOCS: Record<string, DocEntry> = ${JSON.stringify(Object.fromEntries(entries.map((e) => [e.meta.slug, e])), null, 2)};\n`,
);

console.log(`gen-docs: wrote ${entries.length} component doc(s).`);
